### PR TITLE
D8CORE-4380: updating the SOE link style.

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Updated the hover to be 5px on the SOE mixin link style
- Changed the line-height on the `h2` to be 1.5
- Updated the pull request template to @cjwest's standard one.

# Review By (Date)
- 7/8

# Criticality
- High
- Only fixes to this subtheme.

# Urgency
- High (There are accessibility implications with the hover and line-height)

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Rebuild Cache and import config `drush cr ; drush ci`
3. Navigate to /publications, /news, /events.
4. Verify the `h2`s now have a 1.5 line night
5. Verify there is a thicker hover on the black bottom border of 5px.
6. Create some lists with cards and default for news, events, publications. 
7. Verify the line height is there for the `h2`. This is where you'd really see the difference.
8. Verify the bottom borders are 5px on the hover too. 
9. Verify the same on a node page in the 3 across cards.

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory?

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [x] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [x] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [x] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Only the SOE subtheme

# Associated Issues and/or People
- D8CORE-4380

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by pookmish** [comment]
The only thing I see that might be unwanted is the underline goes under the arrow in a teaser paragraph: 
image

**Comment by jenbreese** [comment]
It does that on Production sites too: https://bioengineering.stanford.edu/news/scott-delp-receives-muybridge-award
I have to look up the reason.

**Comment by jenbreese** [comment]
I talked to Rachel and said since it is like that on production it is fine.

**Comment by pookmish** [comment]
Ok. thanks for checking. Maybe a future ticket for that? :shrug:

**Review by pookmish — APPROVED** [review]

**Pull request merged**
