### PR TITLE
D8CORE-2446: Setting up hero banners for SOE

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Changing display for the hero banner. On all mobile views the text should appear on the gradient.

# Needed By (Date)
- Friday

# Urgency
- Med

# Steps to Test

1. Pull in this branch
2. Build
3. Add a hero banner to a page. Verify it matches the designs in the ticket.
https://stanfordits.atlassian.net/browse/D8CORE-2446

# Affected Projects or Products
- SOE Subtheme

# Associated Issues and/or People
- D8CORE-2446

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by jenbreese** [comment]
@imonroe ok. i fixed it up.

**Comment by imonroe** [comment]
I am having problems getting this to work... is there any other stuff I need to switch branches on?

image

**Comment by jenbreese** [comment]
Try using this background image. It mostly looks like I would expect. The padding on the top is off.

**Comment by jenbreese** [comment]
@imonroe Did you try it with the gradient image background?

**Comment by imonroe** [comment]
image

The top of the banner still looks wonky to me.  Another weird thing (though not in the scope of this ticket) is that the media browser pop-up doesn't work in the editing window unless I disable my adblocker.

**Comment by jenbreese** [comment]
This is what mine looks like.
Screen Shot 2020-08-04 at 8 04 02 AM

**Comment by imonroe** [comment]
I pulled in the latest changes, cleared my caches and created a new one, but it still doesn't look like yours.

**Comment by jenbreese** [comment]
are you creating ones in the Hero area or as a paragraph?

**Comment by jenbreese** [comment]
Ok I think that's why.
Screen Shot 2020-08-04 at 8 17 48 AM

**Comment by jenbreese** [comment]
@rmundstock and @kerri-augenstein Should there be a text limit on the banner? Check out the screenshots if we add too much content. What should the behavior be? Should it be handled with documentation or a character limit? Or do we expect authors to not do this?

**Comment by imonroe** [comment]
> are you creating ones in the Hero area or as a paragraph? I wonder if it is the volume of text? Mine are quite short. Let me try that.

I was creating them in the Hero area.

**Comment by rmundstock** [comment]
I'm fine with a character limit, Ishi may be the best person to ask for a number

**Comment by jenbreese** [comment]
@imonroe Ok. I got the ok on no character limits and I fixed the conflicts. :)

**Pull request merged**
