### PR TITLE
D8CORE-2445: adding back the underline to buttons on hover/focus

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Adding underline back to the button. Also added the pull request file for github.

# Review By (Date)
- Friday

# Criticality
- Med

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Add a text area. Add buttons that have the SOE classes. Such as:
```
<a class="su-button soe-button--orange">Regular button</a>
<a class="su-button soe-button--pink">Regular button</a>
<a class="su-button soe-button--turquoise">Regular button</a>
```
3. The buttons change color correctly.  The text should be #000 and the hover the SU Black with white text.

## Front End Validation
- [x] Is the markup using the appropriate semantic tags and passes HTML validation?
- [x] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [x] Is there anything included in this PR that is not related to the problem it is trying to solve? - It has the pull request template in it too.
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- SOE Subtheme.

# Associated Issues and/or People
- D8CORE-2445

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by jenbreese** [comment]
Did you add the soe-button--pink/orange or turquoise class to the link? You have to add the class to use the button colors on the WYSIWYG.

**Comment by jenbreese** [comment]
@imonroe Did adding the button color class work?

**Comment by imonroe** [comment]
image

Yields this:

image

But on the rendered page, it looks like this:

image


I don't know if that's enough to hold up this PR, but I want to make sure that's the behavior you expect?

**Comment by jenbreese** [comment]
@rmundstock What do you think of @imonroe's comment? I know we talked about it a bit last week about the links not being ideal.

**Comment by rmundstock** [comment]
@jenbreese @imonroe it's not ideal that the color does not change in the WYSIWYG editor, but it's good enough for the time being. They have the ability to change the color on the rendered page.

Updating within the editor may be prioritized after the sites launch.

**Comment by imonroe** [comment]
In that case, GTG.

**Pull request merged**
