### PR TITLE
D8CORE-2690: fixing colors for the person node page

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Fixing the colors and links on SOE basic.

# Review By (Date)
- Tuesday

# Criticality
- Med

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to to person node
3. verify the colors look right for the links. Add a card and a bunch of buttons and verify they look like SOE. There are more screenshots in the ticket. 

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Stanford basic theme and the Person module

# Associated Issues and/or People
- D8CORE-2650
- https://github.com/SU-SWS/stanford_person/pull/115

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by jenbreese** [comment]
@sherakama can this issue of nesting depth be excused? It is to get to the ::after the right color for the colored background.

**Comment by imonroe** [comment]
I vote that the nesting depth thing is no big deal, but I'll defer to Shea.

**Comment by jenbreese** [comment]
@sherakama Can you comment on the nesting depth for this one?

**Comment by sherakama** [comment]
Yeah, we hit 4 quite often when we style links. I'll bump up the config to 5.

**Comment by sherakama** [comment]
GTG

**Review by imonroe — APPROVED** [review]
G2G

**Pull request merged**
